#!./cgi-fcgi-interp -c10,-M1,perl
# -*- perl -*-

use warnings;
use strict;

BEGIN {
    open REALSTDERR, ">&2";
}

$SIG{'TERM'} = sub {
    eval { print REALSTDERR "[$$ real-stderr] closing\n"; };
    exit 15;
};

use FCGI;

my $count = 0;
my $request = FCGI::Request();

warn "[$$ starting]";
print STDERR "[$$ stderr starting]\n";
print REALSTDERR "[$$ real-stderr starting]\n";

while ($request->Accept >= 0) {
    my $ua = $ENV{HTTP_USER_AGENT} // '<none>';
    print <<END;
Content-Type; text/plain

success
count=$count
$ua
END
    print STDERR "[$$ stderr] serviced $count ($ua).\n";
    print REALSTDERR "[$$ real-stderr] serviced $count ($ua).\n";
    $count++;
}
